In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)

In [3]:
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [4]:
x.data

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [19]:
x.grad

In [20]:
x.grad_fn

In [21]:
y = x + 2

In [22]:
y

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [23]:
y.grad_fn

In [24]:
z = y * y * 3

In [25]:
out = z.mean()

In [26]:
out

tensor(27.)

In [27]:
x.grad

In [28]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
None
True


In [30]:
out.backward()
print(x.grad)

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [31]:
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [32]:
x = torch.ones(2, 2, requires_grad=True)

In [33]:
y = x + 2

In [34]:
y.backward(torch.ones(2, 2), retain_graph=True)

In [35]:
x.grad

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [36]:
z = y * y

In [37]:
z

tensor([[ 9.,  9.],
        [ 9.,  9.]])

In [38]:
gradient = torch.randn(2, 2)

In [39]:
y.backward(gradient)

In [40]:
x.grad

tensor([[-0.2190,  1.1664],
        [ 0.0082,  0.5328]])

In [41]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
