In [1]:
import torch

In [2]:
a = torch.empty(5, 7, dtype=torch.float)

In [3]:
a

tensor([[-2.8728e+03,  4.5666e-41, -2.8728e+03,  4.5666e-41,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  4.6243e-44,  0.0000e+00,  7.2187e+13,
          3.0829e-41, -2.8727e+03]])

In [4]:
a = torch.randn(5, 7, dtype=torch.double)

In [5]:
a

tensor([[-0.7114,  0.2709,  1.1128,  0.2544,  0.1611,  0.8545,  0.3336],
        [-1.4843,  1.8128, -0.1618,  1.3610, -0.2279, -0.1051, -0.7769],
        [ 1.7740,  0.8399,  1.5260, -0.9753,  1.5130, -0.9687,  1.0517],
        [ 0.6137, -0.1152,  0.5821, -1.8185,  1.2184,  0.2682, -0.6889],
        [-0.2747,  2.1217,  0.0288, -0.4653,  0.8489, -1.0712, -0.5544]], dtype=torch.float64)

In [6]:
a.size()

torch.Size([5, 7])

In [7]:
a.fill_(3.5)

tensor([[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000]], dtype=torch.float64)

In [8]:
a

tensor([[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000]], dtype=torch.float64)

In [9]:
b = a.add(4.0)

In [10]:
b

tensor([[ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000]], dtype=torch.float64)

In [11]:
print(a, b)

tensor([[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
        [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000]], dtype=torch.float64) tensor([[ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000]], dtype=torch.float64)


In [12]:
b = a[0, 3]

In [13]:
b

tensor(3.5000, dtype=torch.float64)

In [14]:
b = a[:, 3:5]

In [15]:
b

tensor([[ 3.5000,  3.5000],
        [ 3.5000,  3.5000],
        [ 3.5000,  3.5000],
        [ 3.5000,  3.5000],
        [ 3.5000,  3.5000]], dtype=torch.float64)

In [16]:
x = torch.ones(5, 5)

In [17]:
x

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
z = torch.empty(5, 2)

In [19]:
z

tensor([[-2.8727e+03,  4.5666e-41],
        [ 8.6119e+13,  3.0829e-41],
        [ 4.4842e-44,  0.0000e+00],
        [ 1.6415e-07,  1.8367e-07],
        [ 6.7262e-44,  0.0000e+00]])

In [20]:
z[:, 0] = 10
z[:, 1] = 100

In [21]:
z

tensor([[  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.],
        [  10.,  100.]])

In [22]:
x.index_add_(1, torch.tensor([4, 0], dtype=torch.long), z)
x

tensor([[ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.],
        [ 101.,    1.,    1.,    1.,   11.]])

In [25]:
x.index_add_(1, torch.tensor([2, 2], dtype=torch.long), z)

tensor([[ 101.,    1.,  221.,    1.,   11.],
        [ 101.,    1.,  221.,    1.,   11.],
        [ 101.,    1.,  221.,    1.,   11.],
        [ 101.,    1.,  221.,    1.,   11.],
        [ 101.,    1.,  221.,    1.,   11.]])

In [26]:
a = torch.ones(5)

In [27]:
a

tensor([ 1.,  1.,  1.,  1.,  1.])

In [28]:
b = a.numpy()

In [29]:
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [30]:
a.add_(1)

tensor([ 2.,  2.,  2.,  2.,  2.])

In [31]:
b

array([ 2.,  2.,  2.,  2.,  2.], dtype=float32)

In [32]:
import numpy as np

In [33]:
a = np.ones(5)
b = torch.from_numpy(a)

In [34]:
b

tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)

In [35]:
np.add(a, 1, out=a)

array([ 2.,  2.,  2.,  2.,  2.])

In [36]:
a

array([ 2.,  2.,  2.,  2.,  2.])

In [37]:
b

tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)

In [38]:
np.add(a, 1)

array([ 3.,  3.,  3.,  3.,  3.])

In [39]:
a

array([ 2.,  2.,  2.,  2.,  2.])

In [40]:
b

tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)

In [41]:
torch.cuda.is_available()

True

In [44]:
if torch.cuda.is_available():
    a = torch.full((10, ), 3, device=torch.device('cuda'))
    print(type(a))
    b = a.to(torch.device('cpu'))
    print(type(b))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [43]:
a

tensor([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.], device='cuda:0')

In [45]:
b

tensor([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])